title: Jairo Suárez
description: My Personal Blog and Web page
author: Jairo Suárez
logo: /static/img/avatar.jpg
github: https://github.com/jairoasuarez
about: Estudiante

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: jairoasuarez
google_analytics: UA-72862926-1

share:
  twitter_username: \jairoasuarez
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
